### ISSUE TITLE
main.CRITICAL: Exception: Notice: Array to string conversion in ConfigFieldPlugin.php

### ISSUE THREAD

**Issue by jorgb90** [avstudnitz/AvS_ScopeHint2#31]
I think this issue arised because of the latest update?

[2022-11-02T10:16:51.485009+00:00] main.CRITICAL: Exception: Notice: Array to string conversion in /public_html/vendor/avstudnitz/scopehint2/Plugin/ConfigFieldPlugin.php on line 138 in /public_html/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 /public_html/vendor/avstudnitz/scopehint2/Plugin/ConfigFieldPlugin.php(138): Magento\Framework\App\ErrorHandler->handler()
#1 /public_html/vendor/avstudnitz/scopehint2/Plugin/ConfigFieldPlugin.php(67): AvS\ScopeHint\Plugin\ConfigFieldPlugin->getScopeHint()
#2 /public_html/vendor/magento/framework/Interception/Interceptor.php(146): AvS\ScopeHint\Plugin\ConfigFieldPlugin->afterGetTooltip()
#3 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Model\Config\Structure\Element\Field\Interceptor->Magento\Framework\Interception\{closure}()
#4 /public_html/generated/code/Magento/Config/Model/Config/Structure/Element/Field/Interceptor.php(32): Magento\Config\Model\Config\Structure\Element\Field\Interceptor->___callPlugins()
#5 /public_html/vendor/magento/module-config/Block/System/Config/Form.php(369): Magento\Config\Model\Config\Structure\Element\Field\Interceptor->getTooltip()
#6 /public_html/vendor/magento/module-config/Block/System/Config/Form.php(316): Magento\Config\Block\System\Config\Form->_initElement()
#7 /public_html/vendor/magento/module-config/Block/System/Config/Form.php(256): Magento\Config\Block\System\Config\Form->initFields()
#8 /public_html/vendor/magento/module-config/Block/System/Config/Form.php(202): Magento\Config\Block\System\Config\Form->_initGroup()
#9 /public_html/vendor/magento/module-config/Block/System/Config/Form.php(542): Magento\Config\Block\System\Config\Form->initForm()
#10 /public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1094): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#11 /public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#12 /public_html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#13 /public_html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#14 /public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#15 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#16 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#17 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#18 /public_html/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement()
#19 /public_html/var/view_preprocessed/pub/static/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(1): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#20 /public_html/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/pu...')
#21 /public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render()
#22 /public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent()
#23 /public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}()
#24 /public_html/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins()
#25 /public_html/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render()
#26 /public_html/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#27 /public_html/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#28 /public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#29 /public_html/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#30 /public_html/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#31 /public_html/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#32 /public_html/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#33 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#34 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#35 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#36 /public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#37 /public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#38 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#39 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#40 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#41 /public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#42 /public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#43 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#44 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#45 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#46 /public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#47 /public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#48 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#49 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#50 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#51 /public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#52 /public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#53 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#54 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#55 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#56 /public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#57 /public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#58 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#59 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#60 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#61 /public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#62 /public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#63 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#64 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#65 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#66 /public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#67 /public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#68 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#69 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#70 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#71 /public_html/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#72 /public_html/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#73 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#74 /public_html/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#75 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#76 /public_html/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement()
#77 /public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout->getOutput()
#78 /public_html/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#79 /public_html/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#80 /public_html/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Layout->renderResult()
#81 /public_html/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#82 /public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#83 /public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#84 /public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#85 {main} [] []

**Comment by jorgb90** [comment]
Solved with pull https://github.com/avstudnitz/AvS_ScopeHint2/pull/30
